---
title: "Form Triplet Motifs"
author: "Ignatius Pang"
date: "8 May 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(igraph)
library(dplyr)

setwd("/home/ignatius/PostDoc/2017/Network_SURF")

base_directory <- getwd()
 
# base_directory <- "/home/ignatius/Documents/Postdoc/2016/Triplet_Motifs/"
data_directory <- file.path( base_directory, "Data/R_Data") 

load( file.path(data_directory, "network_data_library.Rdata"))


```

## Load genetic interactions network table
```{r}

filtered_costanzo_stringent <- filtered_costanzo_stringent_2016 %>% 
								dplyr::select( one_of( c( "query_oln_id_edited",
														  "array_oln_id_edited",
											  "genetic_interaction_score"))) %>%
								dplyr::rename( node_a = query_oln_id_edited,
											   node_b= array_oln_id_edited )

# Clean the table up, such that the node A ID string is always greater than the node B ID string
# This removes the symmetry in the triplet motif dataset 
a_gt_b <- dplyr::filter( filtered_costanzo_stringent, node_a >= node_b   )

b_gt_a <- dplyr::filter( filtered_costanzo_stringent, node_b > node_a   ) %>%
		  dplyr::rename( node_a=node_b, node_b=node_a ) 

# If the genetic interaction has been screen more than once, get the least negative score out of the repeated screens
filtered_costanzo_stringent <- dplyr::union( a_gt_b, b_gt_a) %>%
							   dplyr::group_by( node_a, node_b) %>%
							   dplyr::summarise(max_gi_score = max(genetic_interaction_score) ) %>%
							   dplyr::rename( genetic_interaction_score=max_gi_score) %>%
							   dplyr::ungroup()


# Show what the table look like now 
head( filtered_costanzo_stringent ) 

# Count the unique number of proteins in triplet motifs
length ( unique(  c(as.vector(as.data.frame(filtered_costanzo_stringent)[, "node_a"]) , 
					as.vector (as.data.frame( filtered_costanzo_stringent)[, "node_b"] )) ) )

```

```{r}
# All other biological networks, protein-protein, kinase-substrate, transcription factor-target gene, 
# Combined together into one table 

# tf_network_collated  is the transcriptional regulatory network
# kinase_network_collated  is the kinase-substrate network
# sbi_interactome_collated  is the protein-protein interaction network

interactions_combined <- dplyr::bind_rows(tf_network_collated, kinase_network_collated, sbi_interactome_collated)

head( interactions_combined)

# Rename the tables
interactions_combined_1 <- interactions_combined %>%
							dplyr::rename( node_a = oln_id_a, 
										   node_c= oln_id_b, 
										   type_ac_long = interaction_type,
										   type_ac = interaction_type_abbrev)

interactions_combined_2 <- interactions_combined %>%
							dplyr::rename( node_b = oln_id_a, 
										   node_c= oln_id_b, 
										   type_bc_long = interaction_type,
										   type_bc = interaction_type_abbrev )

```

```{r}
## Join the networks together to find triplets where at least one edge is a negative genetic interaction 


# Join the genetic interaction to the other biological networks
triplet_motifs <- dplyr::inner_join( filtered_costanzo_stringent,
									 interactions_combined_1, by="node_a" )  %>%
	
	# Closing the triplets with a third edge from the other biological networks 
	dplyr::inner_join( interactions_combined_2, by=c("node_b"= "node_b", 
													 "node_c"= "node_c") ) %>%
	# Select the corresponding columns
	dplyr::select ( one_of( c("node_a", "node_b", "node_c", 
							  "type_ac", "type_bc", 
							  "type_ac_long", "type_bc_long",
							  "genetic_interaction_score"))) %>%
	
    # Remove special cases where Node A == Node C or Node B == Node C
    dplyr::filter ( node_a != node_c) %>%
	dplyr::filter ( node_b != node_c) %>%
	
	# Remove duplicates
	dplyr::distinct() %>%
	
	# Arrange the columns in the order that I want 
	dplyr::arrange( node_a, node_b, node_c, type_bc, type_ac)
					 
triplet_motifs

## Count the number of motifs
nrow( triplet_motifs)

```


```{r}

# Count the number of each type of triplet motifs

# Count the cases where type_ac is greater than type_bc (e.g. string comparison)
a_ge_b <- filter( triplet_motifs, type_ac >= type_bc ) %>%
		group_by( type_ac, type_bc) %>%
		summarise(counts=n())

# Count the cases where type_bc is greater than type_ac (e.g. string comparison)
b_gt_a <- filter( triplet_motifs, type_bc > type_ac ) %>%
		group_by( type_ac, type_bc) %>%
		summarise(counts=n()) %>%
		rename ( type_ac= type_bc, type_bc = type_ac) %>%
		select( one_of( c("type_ac", "type_bc", "counts") ))
	
# Merge the above results together
triplet_motif_counts <- dplyr::union( a_ge_b, b_gt_a)  %>%
		group_by( type_ac, type_bc) %>% 
		summarise(total_count=sum(counts)) %>%
		arrange( type_ac, type_bc)

# Here is the final results
triplet_motif_counts

dim( triplet_motif_counts)

triplet_motif_counts <- as.data.frame(triplet_motif_counts)

triplet_motif_counts <- mutate( triplet_motif_counts, 
						motif_type = paste(type_ac, type_bc, sep="") )  %>%
						arrange ( desc(total_count))

triplet_motif_counts[, "motif_type"] <- factor (
	as.vector(triplet_motif_counts[,"motif_type"]),
	levels=as.vector(triplet_motif_counts[,"motif_type"]))

library(ggplot2)

ggplot ( triplet_motif_counts, aes(motif_type, total_count)) + 
	geom_point()

```
