---
title: "random number generator"
author: "Ignatius Pang"
date: "7 May 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(parallel)

```


## Test Random Numbers


```{r }

## Randomly sample 1 number from 1 to 100 
sample_1_number <- function( random_seed , set_random_nubmer_seed =TRUE) { 
	
	if ( set_random_nubmer_seed == TRUE) {
		
					set.seed(random_seed)

	}

	return( sample ( 1:100, 1) ) 
	
} 
```

```{r }

random_number_seed <-10052017
number_of_cpu_cores <- 3
reset_each_time <- TRUE  # set to TRUE to ensure the random number seed is set each time you run

set.seed(random_number_seed )

# Get the two lists of random numbers vectors
random_num_list_1 <- mclapply(1:10 , FUN=sample_1_number, set_random_nubmer_seed= reset_each_time,  mc.cores = number_of_cpu_cores) 
random_num_list_2 <- mclapply(11:20 , FUN=sample_1_number, set_random_nubmer_seed= reset_each_time, mc.cores = number_of_cpu_cores) 

random_num_list_1 <- paste( unlist( random_num_list_1 ), collapse=", ")
random_num_list_2 <- paste( unlist ( random_num_list_2), collapse=", ")

print ( "Different runs with different random number seeds should give differen results")

print ( paste ("List 1: ", random_num_list_1 ) )
print ( paste( "List 2:",  random_num_list_2 )  ) 

# Get the two lists of random numbers vectors
random_num_list_3 <- mclapply(1:10 , FUN=sample_1_number ,  set_random_nubmer_seed= reset_each_time, mc.cores = number_of_cpu_cores) 
random_num_list_4 <- mclapply(11:20 , FUN=sample_1_number ,  set_random_nubmer_seed= reset_each_time, mc.cores = number_of_cpu_cores) 

random_num_list_3 <- paste(unlist ( random_num_list_3 ), collapse=", ")
random_num_list_4 <- paste(unlist ( random_num_list_4 ), collapse=", ")

print ( "Can we reproduce the results of run 1 and 2 again if we provide the same random number seeds?")	
print ( paste( "List 3: ", random_num_list_3) )
print ( paste( "List 4: ", random_num_list_4) ) 

```



## Functions to check if two lists of vectors are exactly the same (deprecated)
```{r}
## Check if two vectors of numbers are the same
is_two_vectors_the_same <- function (  vector_1, vector_2 ) {
	
	if(  length ( which (  vector_1 != vector_2 ) ) >= 1 ) {
		
		return (FALSE )
	}
	
	return( TRUE ) 
	
}

## Check if two lists, each list containig a list of vectors, are the same
is_two_lists_of_vectors_the_same <- function ( list_1, list_2) {
	
   if( 	length(list_1) != length(list_2) ) {
   	  return(FALSE)
   }
	
	results <- lapply ( seq_along( list_1), function(x) { return( is_two_vectors_the_same(list_1[[x]], list_2[[x]] ) ) } )
	
	if(  length ( which (  results  == FALSE) ) >= 1 ) {
		
		return (FALSE )
	}
	
	return( TRUE ) 
	
	
}

# # Compare if the two lists of random numbers vectors are the same
# print ( "Is list 1 reproducing the results of list 2?")
# is_two_lists_of_vectors_the_same( random_num_list_1, random_num_list_2)

# 
# print ( "Is list 3 reproducing the results of list 1?")
# is_two_lists_of_vectors_the_same( random_num_list_1, random_num_list_3 ) 
# 
# print ( "Is list 4 reproducing the results of list 2?")
# is_two_lists_of_vectors_the_same( random_num_list_2, random_num_list_4 ) 

```




